/* ============================================================
 * IMPORTANT: This file is INCOMPLETE.
 * The PDF report only captured two sections of this file in
 * its screenshots (lines 24-93 and lines 360-440).
 * The middle section (lines 94-359), which contains all the
 * HAL peripheral initialisations and RTOS task definitions
 * generated by STM32CubeIDE, was NOT visible in any screenshot.
 *
 * To fully restore this project, regenerate main.c from the
 * original .ioc configuration file using STM32CubeIDE and
 * paste in the USER CODE sections shown below.
 * ============================================================ */

/* ---- SECTION 1: lines 24-93 (USER CODE sections) ---------- */

/* USER CODE BEGIN Includes */
#include "temp.h"
#include "queue.h"
/* USER CODE END Includes */

/* USER CODE BEGIN PV */
QueueHandle_t xQueue = NULL;  // Queue handle for inter-thread communication
/* USER CODE END PV */

/* Private function prototypes */
void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_DMA_Init(void);
static void MX_USART2_UART_Init(void);
static void MX_I2C1_Init(void);
static void MX_SPI1_Init(void);
void StartI2CTask(void const *argument);
void StartTaskBSPI(void const *argument);

/* USER CODE BEGIN PFP */
/* USER CODE END PFP */

/* USER CODE BEGIN 0 */
/* USER CODE END 0 */

/**
 * @brief The application entry point.
 * @retval int
 */
int main(void)
{
    /* USER CODE BEGIN 1 */
    xQueue = xQueueCreate(10, 2 * sizeof(uint8_t));  // Create the queue
    /* USER CODE END 1 */

    /* ========================================================
     * MISSING: lines 94-359
     * This section contains HAL_Init(), SystemClock_Config(),
     * peripheral initialisations (GPIO, DMA, UART, I2C, SPI),
     * and osKernelInitialize() / osThreadNew() calls generated
     * by STM32CubeIDE. It was not captured in the PDF screenshots.
     * ======================================================== */
}

/* ---- SECTION 2: lines 360-440 (Task functions) ------------ */

/* USER CODE END Header_StartI2CTask */
void StartI2CTask(void const *argument)
{
    /* USER CODE BEGIN 5 */
    uint8_t data_to_send[2];

    /* Infinite loop */
    for (;;)
    {
        // Retrieve the raw temperature data from the TMP102 sensor via I2C + DMA
        int16_t rawValue = i2c_communicate(&hi2c1, &huart2);

        if (rawValue)  // Check if rawValue is non-zero before processing
        {
            // Pack the 12-bit value into two bytes for SPI transmission
            data_to_send[0] = (uint8_t)(rawValue >> 4);           // Upper 8 bits
            data_to_send[1] = (uint8_t)((rawValue & 0xF) << 4);   // Lower 4 bits in high nibble

            // Send the processed data to the queue (blocks if full)
            xQueueSend(xQueue, data_to_send, portMAX_DELAY);
        }

        // Also print the temperature on the master side via UART for debugging
        i2c_processResult(rawValue, &huart2);
        osDelay(1000);
    }
    /* USER CODE END 5 */
}

void StartTaskBSPI(void const *argument)
{
    /* USER CODE BEGIN StartSPITask */
    uint8_t data_to_send[2];

    /* Infinite loop */
    for (;;)
    {
        // Block until data is available in the queue
        if (xQueueReceive(xQueue, &data_to_send, portMAX_DELAY) == pdPASS)
        {
            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_RESET);  // SS Low (Select Slave)

            HAL_SPI_Transmit(&hspi1,
                             data_to_send,
                             2,
                             HAL_MAX_DELAY);

            HAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, GPIO_PIN_SET);    // SS High (Deselect Slave)
        }
        osDelay(1000);
    }
    /* USER CODE END StartSPITask */
}
