/* ============================================================
 * IMPORTANT: This file is INCOMPLETE.
 * The PDF report only captured lines 100-110 of this file
 * (the while-loop body inside main). The full file includes
 * HAL/RTOS initialisations generated by STM32CubeIDE that
 * were not visible in any screenshot.
 *
 * The slave program is simpler than the master: it waits for
 * 2 bytes over SPI, then converts and prints the temperature
 * via UART (e.g. PuTTY at 115200 baud).
 *
 * To fully restore, regenerate main.c from the .ioc file in
 * STM32CubeIDE and paste in the USER CODE sections below.
 * ============================================================ */

/* ========================================================
 * MISSING: All code before line 100
 * Includes: HAL_Init(), SystemClock_Config(), MX_GPIO_Init(),
 * MX_SPI1_Init(), MX_USART2_UART_Init(), and the start of
 * main() up to the while loop.
 * ======================================================== */

/* USER CODE BEGIN Includes */
#include "temp.h"
/* USER CODE END Includes */

int main(void)
{
    /* ========================================================
     * MISSING: peripheral initialisations (lines ~1-99)
     * ======================================================== */

    /* USER CODE BEGIN WHILE */
    uint8_t slaveRxData[2];  // Buffer to receive data

    while (1)
    {
        // Receive 2 bytes of SPI data with a 1000 ms timeout
        if (HAL_SPI_Receive(&hspi1, slaveRxData, 2, 1000) == HAL_OK)
        {
            i2c_processResult(slaveRxData, &huart2);
        }
    }
    /* USER CODE END WHILE */
}
